---
- name: Backup device configurations
  hosts: all
  gather_facts: no  # CHANGED: Don't gather facts from network devices
  vars:
    backup_dir: "{{ playbook_dir }}/backups"
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    
  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost
      
    - name: Get running configuration (mock for testing)
      set_fact:
        running_config:
          stdout: |
            ! Mock configuration for {{ inventory_hostname }}
            hostname {{ inventory_hostname }}
            interface lo
             ip address {{ loopback_ip | default('1.1.1.1/32') }}
            router ospf
             ospf router-id {{ ospf_router_id | default('1.1.1.1') }}
            router bgp {{ bgp_asn | default('65001') }}
            
    - name: Save configuration to backup file
      copy:
        content: |
          ! Backup created: {{ timestamp }}
          ! Device: {{ inventory_hostname }}
          ! BGP ASN: {{ bgp_asn }}
          ! Loopback: {{ loopback_ip }}
          ! OSPF Router ID: {{ ospf_router_id }}
          ! Source: Mock data for testing
          !
          {{ running_config.stdout }}
        dest: "{{ backup_dir }}/{{ inventory_hostname }}/{{ timestamp }}-running.txt"
      delegate_to: localhost
      
    - name: Display backup status
      debug:
        msg: "✅ Backup saved for {{ inventory_hostname }} at {{ timestamp }}"
