---
- name: Collect FRR device facts
  hosts: all
  gather_facts: no  # CHANGED: Don't gather facts from network devices
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    epoch: "{{ lookup('pipe', 'date +%s') }}"
  
  tasks:
    - name: Create facts directory
      file:
        path: "{{ playbook_dir }}/facts"
        state: directory
      delegate_to: localhost
      run_once: yes
      
    - name: Test container connectivity
      raw: echo "Testing {{ inventory_hostname }}"
      register: connectivity_test
      ignore_errors: yes
      
    - name: Create device facts (with manual timestamp)
      set_fact:
        device_facts:
          hostname: "{{ inventory_hostname }}"
          version: "{{ software_version | default('FRRouting 8.4_git') | regex_search('FRRouting ([0-9._]+)', '\\1') | first | default('8.4') }}"
          serial: "{{ epoch }}"
          status: "{{ 'active' if connectivity_test is succeeded else 'mock' }}"
          bgp_asn: "{{ bgp_asn }}"
          loopback_ip: "{{ loopback_ip }}"
          ospf_router_id: "{{ ospf_router_id }}"
          ospf_area: "{{ ospf_area }}"
          interfaces: []
          collected_at: "{{ timestamp }}"
          
    - name: Save facts to JSON file
      copy:
        content: "{{ device_facts | to_nice_json }}"
        dest: "{{ playbook_dir }}/facts/{{ inventory_hostname }}_facts.json"
      delegate_to: localhost
      
    - name: Display facts collection status
      debug:
        msg: "✅ Facts collected for {{ inventory_hostname }}: BGP {{ bgp_asn }}, Loopback {{ loopback_ip }}, Status {{ device_facts.status }}"
